name: build PRs

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  build-binary:
    name: build-binary
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build artifacts
        run: |
          docker build . -t builder
          docker run --rm -v ${PWD}:/project builder python3 build.py
      - name: Upload Aroma version
        uses: actions/upload-artifact@v3
        with:
          name: NUSspli-Aroma-DEBUG
          path: out/Aroma-DEBUG/*
          if-no-files-found: error
      - name: Upload Lite version
        uses: actions/upload-artifact@v3
        with:
          name: NUSspli-Lite-DEBUG
          path: out/Lite-DEBUG/*
          if-no-files-found: error
      - name: Upload Channel version
        uses: actions/upload-artifact@v3
        with:
          name: NUSspli-Channel-DEBUG
          path: out/Channel-DEBUG/*
          if-no-files-found: error
      - name: Upload HBL version
        uses: actions/upload-artifact@v3
        with:
          name: NUSspli-HBL-DEBUG
          path: out/HBL-DEBUG/*
          if-no-files-found: error
